### ISSUE TITLE
Git clone process (or any other process) is being terminated after 60 seconds for large repositories

### ISSUE THREAD

**Issue by piotrpolak** [kzykhys/PHPGit#13]
```
[Symfony\Component\Process\Exception\ProcessTimedOutException]
  The process "'git' 'clone' '--quiet' 'https://**********.git' '../../*****/'" exceeded the timeout of
  60 seconds.
```

The ProcessBuilder created by Git::getProcessBuilder() has no timeout set so the default timeout of 60s is used.

There is no way to change the behavior of the mentioned method from outside world.

**Comment by kmaid** [comment]
Sounds like you are hitting your php script execution limit. See http://php.net/manual/en/function.set-time-limit.php

**Comment by piotrpolak** [comment]
This is not the php script execution limit because once the `setTimeout(99999)` is added the script works fine (see https://github.com/piotrpolak/PHPGit/commit/e376d3fc2a301d25794353fe8800771d5e2fbb5f)

**Comment by kmaid** [comment]
Did you see the note about "This function has no effect when PHP is running in safe mode. There is no workaround other than turning off safe mode or changing the time limit in the php.ini."

**Comment by cpliakas** [comment]
Cross-posting https://github.com/cpliakas/git-wrapper/issues/92 as the issues sound similar.

**Comment by piotrpolak** [comment]
It seems it won't be fix.
