### ISSUE TITLE
Impossible to get the correct branch name

### ISSUE THREAD

**Issue by blaugueux** [kzykhys/PHPGit#2]
When a branch track a remote branch the branch name is incorrect.

Example : `## master...origin/master [ahead 5]`
Result : `5]`
Expected : `master`

I think the issue is in the regex [here](https://github.com/kzykhys/PHPGit/blob/master/src/PHPGit/Command/StatusCommand.php#L116)

BTW congrats, you did an amazing work with this library :+1:

**Comment by kzykhys** [comment]
Good catch! Thank you for reporting :)

**Comment by blaugueux** [comment]
@kzykhys Thx :+1:
