### ISSUE TITLE
SSH Keys

### ISSUE THREAD

**Issue by bweston92** [kzykhys/PHPGit#7]
Support for SSH key? I don't know if it is just Windows but it handles it really poorly.

**Comment by bweston92** [comment]
If I run the command for cloning from the command line it works, but from the app it gets a permission denied, maybe it isn't receiving the GIT_SSH env variable?

**Comment by Cosmicist** [comment]
I'm using [Codex](http://codex.caffeinated.ninja) which uses this library for using Git and I'm trying to add a private repo, so I really need this feature. Is it available and not documented? Couldn't find anything yet.

**Comment by DarkAxi0m** [comment]
i have the git-scm install on git on windows, using git bash works with keys.  
To get phpgit to work with keys im trying to wrap all commands with `"C:\Program Files (x86)\Git\bin\bash.exe" --login -c '%commandhere%'`

no real luck yet though.
